### ISSUE TITLE
Remediation for fragile dependency on ophyd PR branch

### ISSUE THREAD

**Issue by danielballan** [bluesky/suitcase-utils#19]
Proposed remediation for https://github.com/NSLS-II/ophyd/pull/682#issuecomment-477997775:

1. Make a special branch on ophyd's upstream fork, `ophyd-for-suitcase-utils` or something.
2. Update suitcase-utils' `requirements-dev.txt` to point at that instead of Andrew's PR branch.
3. Revert out all of or part of https://github.com/NSLS-II/suitcase-utils/pull/17 to avoid making a release that includes it.
4. Tag and release suitcase-utils.

**Comment by mrakitin** [comment]
Good plan. Where do you want that upstream fork? NSLS-II org?

**Comment by mrakitin** [comment]
I created the repo https://github.com/NSLS-II/ophyd-for-suitcase-utils. The master branch matches this commit from @awalter-bnl's branch: https://github.com/NSLS-II/ophyd/pull/682/commits/bebb6177d6bb87ed990fa4ce8ff429244e332153.

**Comment by tacaswell** [comment]
Probably better to do this with a branch rather than a new repo!

**Comment by mrakitin** [comment]
Alright, I removed the new repo, and created a new branch instead: https://github.com/NSLS-II/ophyd/tree/ophyd-for-suitcase-utils. Are we good to proceed with the next steps?

**Comment by danielballan** [comment]
This is actually more involved than I realized at first. Every suitcase package must be touched, as in:

https://github.com/NSLS-II/suitcase-csv/blob/master/requirements-dev.txt#L7

**Comment by mrakitin** [comment]
Why don't we just remove the dependency on the ophyd from the suitcase packages? They all depend on suitcase-utils, which, in turn, depends on https://github.com/NSLS-II/suitcase-utils/blob/46658d2699ad6e2d1716360f142889d6adafdd0c/requirements-dev.txt#L11

**Comment by mrakitin** [comment]
FYI, I removed the version 0.1.2 from PyPI which was erroneously placed there before partially reverting #17.

**Comment by danielballan** [comment]
The Devil is in the details here. To be precise, the suitcase packages depend on `suitcase-utils`, which has no ophyd dependency at all. The suitcase packages' _tests_ depend on `suitcase-utils[test_fixtures]`. You  are reasonably asking, why not put the ophyd dependency in `suitcase-utils[test_fixtures]`? In fact we already do that with bluesky: that is, the suitcase packages don't depend directly on bluesky; they get bluesky via `suitcase-utils[test_fixtures]`. Why not do the same with ophyd?

The problem is that there is no way for `pip install suitcase-utils[test_fixtures]` to install a branch from GitHub; the `install_requires` or `extras_require` lists in `setup.py` can only include _published_ packages on PyPI, not GitHub URLs. That's why ophyd is listed specifically in each suitcase package, while bluesky is not. As soon as we release a version of ophyd (or even just an alpha) that has this desired "simulated Device with a configure method" we can consolidate the ophyd dependency in `suitcase-utils[test_fixtures]` and drop it from all the individual suitcase packages.

This is why it may have been easier to define the new simulated Device with the configure method directly in `suitcase-utils` rather than trying to coordinate with a change in ophyd. It was difficult to communicate my reasoning in a way that was convincing, given all the packaging-related details in play. It's clear now that we should have at least depended on a special branch, rather than a PR branch, and it's my fault for not pressing for that before we rolled out so many suitcases.

**Comment by mrakitin** [comment]
Thanks for the explanation, @danielballan. I forgot pip does not play nice with git repos for the source of packages.

**Comment by mrakitin** [comment]
I think I took care of all the updates in:
- https://github.com/NSLS-II/suitcase-csv/pull/12
- https://github.com/NSLS-II/suitcase-jsonl/pull/10
- https://github.com/NSLS-II/suitcase-tiff/pull/24
- https://github.com/NSLS-II/suitcase-specfile/pull/4
- https://github.com/NSLS-II/suitcase-mongo/pull/14

**Comment by danielballan** [comment]
I think this is fixed everywhere. It started generating CI failures, which made it easy to catch the rest. :-D
